import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'

import HomePage from './HomePage/Home' 



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HomePage/>
    </>
  )
}
