const leaddata = [
  {
    id: 1,
    name: "Chetan Saini",
    image: "https://i.pravatar.cc/48",
    species: "warrior",
    status: "21 din baat me skills double",
    points: 30,
    consistency: "4 days",
  },

  {
    id: 2,
    name: "Chetan Saini",
    image: "https://i.pravatar.cc/48",
    species: "warrior",
    status: "21 din baat me skills double",
    points: 30,
    consistency: "4 days",
  },
  {
    id: 3,
    name: "Chetan Saini",
    image: "https://i.pravatar.cc/48",
    species: "warrior",
    status: "21 din baat me skills double",
    points: 30,
    consistency: "4 days",
  },
  {
    id: 4,
    name: "Chetan Saini",
    image: "https://i.pravatar.cc/48",
    species: "warrior",
    status: "21 din baat me skills double",
    points: 30,
    consistency: "4 days",
  },
  {
    id: 5,
    name: "Chetan Saini",
    image: "https://i.pravatar.cc/48",
    species: "warrior",
    status: "21 din baat me skills double",
    points: 30,
    consistency: "4 days",
  },

  {
    id: 6,
    name: "Chetan Saini",
    image: "https://i.pravatar.cc/48",
    species: "warrior",
    status: "21 din baat me skills double",
    points: 30,
    consistency: "4 days",
  },
  {
    id: 7,
    name: "Chetan Saini",
    image: "https://i.pravatar.cc/48",
    species: "warrior",
    status: "21 din baat me skills double",
    points: 30,
    consistency: "4 days",
  },
  {
    id: 8,
    name: "Chetan Saini",
    image: "https://i.pravatar.cc/48",
    species: "warrior",
    status: "21 din baat me skills double",
    points: 30,
    consistency: "4 days",
  },
  {
    id: 9,
    name: "Chetan Saini",
    image: "https://i.pravatar.cc/48",
    species: "warrior",
    status: "21 din baat me skills double",
    points: 30,
    consistency: "4 days",
  },
  {
    id: 10,
    name: "Chetan Saini",
    image: "https://i.pravatar.cc/48",
    species: "warrior",
    status: "21 din baat me skills double",
    points: 30,
    consistency: "4 days",
  },
];
export default leaddata;
